$(document).ready(function(){
	var ajax = new majax;
	ajax.on(
		200,
		function(msg,data){
			$("link").last().addClass("old");
			$("head").append(data["css"]);
			window.setTimeout(function(){
				$("link.old").remove();
				ajax.post(magic_route,{"css_only":true});
			},200);
		}
	);
	ajax.on(
		304,
		function(msg){
			window.setTimeout(function(){
				ajax.post(magic_route,{"css_only":true});
			},200);
		}
	)
	ajax.onError = function(){
		window.setTimeout(function(){
			ajax.post(magic_route,{"css_only":true});
		},200);
	}
	window.setTimeout(function(){
		ajax.post(magic_route,{"css_only":true});
	},2000)
})